import "./globals.css";
import "./glabals.scss";

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Providers from "./providers";
import ThemeButton from "./components/ThemeButton";
import Navbar from "./components/navbars/General_nav";
import AuthContext from "./context/AuthContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className="dark"
      style={{ colorScheme: "light" }}
      suppressHydrationWarning
    >
      <body className={inter.className}>
        <AuthContext>
          <Providers>
            <Navbar />
            <main className=" bg-white  dark:bg-midnight min-h-screen">
              {children}
              <ThemeButton />
            </main>
          </Providers>
        </AuthContext>
      </body>
    </html>
  );
}
